- include: ca.yaml
  when: is_lain_manager

- name: copy self-signed CA root
  copy: src="{{ manager_home }}/.certs/rootCA.crt" dest=/etc/pki/ca-trust/source/anchors/

- name: get rootCA stat
  stat: path=/etc/pki/ca-trust/source/anchors/rootCA.crt
  register: src_stat
  changed_when: False

- name: get cert bundle stat
  stat: path=/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
  register: dest_stat
  changed_when: False

- name: trust self-sigend CA root
  command: update-ca-trust extract
  when: src_stat.stat.mtime > dest_stat.stat.mtime  # src is newer
