- name: copy networkd binary file
  copy:
    src: networkd
    dest: /usr/bin/networkd
    force: yes
    mode: a+x

- name: generate networkd.service
  template:
    src: networkd.service.j2
    dest: /etc/systemd/system/networkd.service

- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: systemctl restart networkd && systemctl enable networkd
  service:
    name: networkd
    state: restarted
    enabled: yes
