- name: stop calico-bird.service
  service:
    name: calico-bird.service
    state: stopped

- name: stop calico-bird6.service
  service:
    name: calico-bird6.service
    state: stopped
    enabled: yes

- name: stop calico-confd.service
  service:
    name: calico-confd.service
    state: stopped
    enabled: yes

- name: stop calico-felix.service
  service:
    name: calico-felix.service
    state: stopped
    enabled: yes

- name: stop calico-libnetwork.service
  service:
    name: calico-libnetwork.service
    state: stopped
    enabled: yes

- file:
    path: /lib/systemd/system/calico-bird.service
    state: absent

- file:
    path: /lib/systemd/system/calico-bird6.service
    state: absent

- file:
    path: /lib/systemd/system/calico-confd.service
    state: absent

- file:
    path: /lib/systemd/system/calico-felix.service
    state: absent

- file:
    path: /lib/systemd/system/calico-libnetwork.service
    state: absent

- file:
    path: /usr/bin/calicoctl
    state: absent

- file:
    path: /usr/bin/calico-upgrade
    state: absent

- file:
    path: /usr/bin/allocate-ipip-addr
    state: absent

- file:
    path: /usr/bin/bird
    state: absent

- file:
    path: /usr/bin/bird6
    state: absent

- file:
    path: /usr/bin/calico-felix
    state: absent

- file:
    path: /usr/bin/confd
    state: absent

- file:
    path: /usr/bin/libnetwork-plugin
    state: absent

- name: deploy calicoctl
  copy: src=/tmp/lain/calicoctl dest=/usr/bin/calicoctl mode=a+x

- name: restore etcd data
  shell: /usr/bin/etcd-restore.sh /var/etcd/etcd.properties
  run_once: true

- name: start calico node
  shell: calicoctl node --libnetwork --node-image={{ calico_node_image }} --libnetwork-image={{ calico_libnetwork_image }} --ip {{ node_ip }}
  environment:
    ETCD_AUTHORITY: 127.0.0.1:{{ etcd_client_port }}