- name: copy etcd2consul binary file
  copy:
    src: bin/etcd2consul
    dest: /usr/bin/etcd2consul
    force: yes
    mode: a+x

- name: rm docker.service
  file:
    path: /etc/systemd/system/docker.service
    state: absent

- name: copy docker.service
  copy:
    src: docker.service
    dest: /lib/systemd/system/docker.service
    force: yes

- name: mkdir /etc/docker
  file: path=/etc/docker state=directory

- name: generate daemon.json
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json

- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: copy etcd data to consul
  command: etcd2consul -etcd 127.0.0.1:{{ etcd_client_port }} -consul 127.0.0.1:8500
  run_once: true

- name: start and enable docker.service
  service:
    name: docker.service
    state: started
    enabled: yes

- name: delete docker network endpoint
  command: consul kv delete -recurse /docker/network/v1.0/endpoint/
